INSERT INTO institutions (name, type, grading_scale, grade_boundaries) VALUES
-- Federal Universities (5.0 Scale)
('University of Ilorin (UNILORIN)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('University of Nigeria, Nsukka (UNN)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('University of Benin (UNIBEN)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal University of Technology, Minna (FUTMINNA)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal University of Technology, Akure (FUTA)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal University of Technology, Owerri (FUTO)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Nnamdi Azikiwe University (UNIZIK)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('University of Jos (UNIJOS)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('University of Abuja (UNIABUJA)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('University of Port Harcourt (UNIPORT)', 'Federal University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),

-- State Universities (5.0 Scale)
('Lagos State University (LASU)', 'State University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Olabisi Onabanjo University (OOU)', 'State University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Ekiti State University (EKSU)', 'State University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Delta State University (DELSU)', 'State University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),

-- Private Universities (5.0 Scale)
('Covenant University', 'Private University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Babcock University', 'Private University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Afe Babalola University (ABUAD)', 'Private University', 5.0, '{"A": {"min_score": 70, "points": 5}, "B": {"min_score": 60, "points": 4}, "C": {"min_score": 50, "points": 3}, "D": {"min_score": 45, "points": 2}, "E": {"min_score": 40, "points": 1}, "F": {"min_score": 0, "points": 0}}'::jsonb),

-- Polytechnics (4.0 Scale)
('Federal Polytechnic, Nekede', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal Polytechnic, Oko', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal Polytechnic, Ede', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Federal Polytechnic, Ado-Ekiti', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Kaduna Polytechnic (KADPOLY)', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Auchi Polytechnic', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Kwara State Polytechnic', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb),
('Rufus Giwa Polytechnic', 'Polytechnic', 4.0, '{"A": {"min_score": 75, "points": 4.0}, "AB": {"min_score": 70, "points": 3.5}, "B": {"min_score": 65, "points": 3.25}, "BC": {"min_score": 60, "points": 3.0}, "C": {"min_score": 55, "points": 2.75}, "CD": {"min_score": 50, "points": 2.5}, "D": {"min_score": 45, "points": 2.25}, "E": {"min_score": 40, "points": 2.0}, "F": {"min_score": 0, "points": 0}}'::jsonb);
