'use client'

import { Printer, ChevronLeft, Download } from 'lucide-react'
import Link from 'next/link'

interface TranscriptClientProps {
  student: any;
  semesters: any[];
}

export default function TranscriptClient({ student, semesters }: TranscriptClientProps) {
  const handlePrint = () => {
    window.print();
  }

  return (
    <div className="min-h-screen bg-gray-50 print:bg-white text-gray-900 pb-20">
      {/* Non-printable controls */}
      <div className="print:hidden max-w-4xl mx-auto p-4 md:p-8 flex justify-between items-center mb-4">
        <Link href="/dashboard" className="flex items-center gap-2 text-gray-500 hover:text-gray-900 transition-colors font-medium">
          <ChevronLeft className="w-5 h-5" /> Back to Dashboard
        </Link>
        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 bg-blue-600 text-white px-5 py-2.5 rounded-xl font-bold hover:bg-blue-700 transition-colors shadow-lg shadow-blue-500/20"
        >
          <Printer className="w-5 h-5" />
          Print / Save PDF
        </button>
      </div>

      {/* Printable Area */}
      <div className="max-w-4xl mx-auto bg-white p-8 md:p-16 shadow-2xl print:shadow-none print:p-0 rounded-2xl print:rounded-none">
        
        {/* Document Header */}
        <div className="border-b-4 border-gray-900 pb-8 mb-8 text-center">
          <h1 className="text-4xl font-black uppercase tracking-widest mb-2">Academic Transcript</h1>
          <h2 className="text-2xl font-bold text-gray-600">{student.institution.name}</h2>
          <p className="text-sm font-medium text-gray-500 mt-2">Generated by FirstClass.ng</p>
        </div>

        {/* Student Details */}
        <div className="grid grid-cols-2 gap-8 mb-12">
          <div>
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">Student Name</p>
            <p className="text-xl font-black">{student.name}</p>
          </div>
          <div>
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">Matric Number</p>
            <p className="text-xl font-black">{student.matric_number || 'N/A'}</p>
          </div>
          <div>
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">Course of Study</p>
            <p className="text-xl font-black">{student.course_of_study}</p>
          </div>
          <div>
            <p className="text-xs font-bold text-gray-400 uppercase tracking-widest mb-1">Grading Scale</p>
            <p className="text-xl font-black">{student.institution.grading_scale.toFixed(1)} Point Scale</p>
          </div>
        </div>

        {/* Semesters Loop */}
        <div className="space-y-12">
          {semesters.length === 0 ? (
            <div className="text-center py-12 text-gray-400 font-medium border-2 border-dashed border-gray-200 rounded-xl">
              No academic records logged yet.
            </div>
          ) : (
            semesters.map((sem, idx) => {
              let semUnits = 0;
              let semPoints = 0;
              sem.grades?.forEach((g: any) => {
                semUnits += g.credit_units;
                semPoints += g.points;
              });
              const semGPA = semUnits > 0 ? (semPoints / semUnits) : 0;

              return (
                <div key={sem.id || idx} className="break-inside-avoid">
                  <div className="flex justify-between items-end border-b-2 border-gray-200 pb-2 mb-4">
                    <h3 className="text-xl font-bold">{sem.level} Level • Term {sem.term}</h3>
                    <div className="text-right">
                      <span className="text-sm font-bold text-gray-500 uppercase tracking-wider">GPA: </span>
                      <span className="text-lg font-black">{semGPA.toFixed(2)}</span>
                    </div>
                  </div>
                  
                  <table className="w-full text-left border-collapse">
                    <thead>
                      <tr className="bg-gray-50">
                        <th className="py-3 px-4 font-bold text-xs uppercase text-gray-500 border border-gray-200">Course Code</th>
                        <th className="py-3 px-4 font-bold text-xs uppercase text-gray-500 border border-gray-200 text-center">Units</th>
                        <th className="py-3 px-4 font-bold text-xs uppercase text-gray-500 border border-gray-200 text-center">Grade</th>
                        <th className="py-3 px-4 font-bold text-xs uppercase text-gray-500 border border-gray-200 text-center">Points</th>
                      </tr>
                    </thead>
                    <tbody>
                      {sem.grades?.map((g: any, gIdx: number) => (
                        <tr key={gIdx}>
                          <td className="py-3 px-4 border border-gray-200 font-bold">{g.course_code}</td>
                          <td className="py-3 px-4 border border-gray-200 text-center font-medium">{g.credit_units}</td>
                          <td className="py-3 px-4 border border-gray-200 text-center font-black">{g.grade}</td>
                          <td className="py-3 px-4 border border-gray-200 text-center font-medium">{g.points}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                  <div className="text-right mt-2 text-sm font-medium text-gray-500">
                    Total Units: {semUnits} | Total Points: {semPoints}
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Final CGPA Summary */}
        {semesters.length > 0 && (
          <div className="mt-16 pt-8 border-t-4 border-gray-900 flex justify-between items-center break-inside-avoid">
            <div>
              <p className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-1">Official Status</p>
              <p className="text-xl font-black text-emerald-600">Active</p>
            </div>
            <div className="text-right">
              <p className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-1">Cumulative Grade Point Average</p>
              <p className="text-5xl font-black text-gray-900">{student.current_cgpa?.toFixed(2) || '0.00'}</p>
            </div>
          </div>
        )}

      </div>
    </div>
  )
}
